import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :family_dashboard, FamilyDashboardWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# This app deploys to exactly one target: a home kiosk device on a trusted LAN,
# with no TLS terminator in front of it (see deploy/README.md). `:force_ssl` is
# baked in at compile time (Phoenix wires `Plug.SSL` into the compiled endpoint
# pipeline from whatever value is visible when this file compiles), so it can't
# be toggled from `runtime.exs` — it must be set here, or left off entirely as
# below. If this app ever gains a public/cloud deployment, reinstate a
# `force_ssl` block for that target.

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
