defmodule FamilyDashboard.Repo.Migrations.AddDailyRefreshSettings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:settings) do
      add :daily_refresh_minutes, :bigint, null: false, default: 60
      add :daily_last_attempted_at, :utc_datetime
    end
  end

  def down do
    alter table(:settings) do
      remove :daily_last_attempted_at
      remove :daily_refresh_minutes
    end
  end
end
