defmodule FamilyDashboard.Repo.Migrations.AddNewsFeedsAndItems do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:news_items, primary_key: false) do
      add :news_feed_id,
          references(:news_feeds, column: :id, name: "news_items_news_feed_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :published_at, :utc_datetime
      add :guid, :text, null: false
      add :url, :text, null: false
      add :title, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:news_feeds, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :last_error, :text
      add :last_fetched_at, :utc_datetime
      add :enabled, :boolean, null: false
      add :label, :text, null: false
      add :url, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:news_items, [:news_feed_id, :guid], name: "news_items_feed_guid_index")
  end

  def down do
    drop_if_exists unique_index(:news_items, [:news_feed_id, :guid],
                     name: "news_items_feed_guid_index"
                   )

    drop table(:news_feeds)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `news_items` table without the `news_items_news_feed_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:news_items)
  end
end