defmodule FamilyDashboard.Repo.Migrations.AddNewsSettings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:settings) do
      # DB defaults match the resource attribute defaults; required by SQLite to
      # add NOT NULL columns to the populated settings table.
      add :news_refresh_minutes, :bigint, null: false, default: 15
      add :news_retention_hours, :bigint, null: false, default: 24
      add :news_last_attempted_at, :utc_datetime
    end
  end

  def down do
    alter table(:settings) do
      remove :news_last_attempted_at
      remove :news_retention_hours
      remove :news_refresh_minutes
    end
  end
end
