defmodule FamilyDashboard.Repo.Migrations.AddNewsItemFeedCascadeDelete do
  @moduledoc """
  Adds `ON DELETE CASCADE` to `news_items.news_feed_id` so deleting a
  `NewsFeed` (e.g. from ash_admin) takes its items with it instead of
  failing on the FK constraint.

  SQLite cannot alter a foreign key constraint in place (see the raised
  error in the autogenerated version of this migration), so this
  hand-writes the standard SQLite recreate-table dance instead.
  """

  use Ecto.Migration

  def up do
    rename table(:news_items), to: table(:news_items_old)

    create table(:news_items, primary_key: false) do
      add :news_feed_id,
          references(:news_feeds,
            column: :id,
            name: "news_items_news_feed_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :published_at, :utc_datetime
      add :guid, :text, null: false
      add :url, :text, null: false
      add :title, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    execute("""
    INSERT INTO news_items
      (news_feed_id, updated_at, inserted_at, published_at, guid, url, title, id)
    SELECT
      news_feed_id, updated_at, inserted_at, published_at, guid, url, title, id
    FROM news_items_old
    """)

    drop table(:news_items_old)

    create unique_index(:news_items, [:news_feed_id, :guid], name: "news_items_feed_guid_index")
  end

  def down do
    rename table(:news_items), to: table(:news_items_old)

    create table(:news_items, primary_key: false) do
      add :news_feed_id,
          references(:news_feeds, column: :id, name: "news_items_news_feed_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :published_at, :utc_datetime
      add :guid, :text, null: false
      add :url, :text, null: false
      add :title, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    execute("""
    INSERT INTO news_items
      (news_feed_id, updated_at, inserted_at, published_at, guid, url, title, id)
    SELECT
      news_feed_id, updated_at, inserted_at, published_at, guid, url, title, id
    FROM news_items_old
    """)

    drop table(:news_items_old)

    create unique_index(:news_items, [:news_feed_id, :guid], name: "news_items_feed_guid_index")
  end
end
