defmodule FamilyDashboard.Repo.Migrations.NormalizeWeather do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:weather_readings) do
      # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
      # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
      # remove :forecast

      add :humidity, :bigint
      add :pressure, :bigint
      add :dew_point, :float
      add :uvi, :float
      add :clouds, :bigint
      add :visibility, :bigint
      add :wind_speed, :float
      add :wind_deg, :bigint
      add :wind_gust, :float
      add :sunrise, :utc_datetime
      add :sunset, :utc_datetime
    end

    create table(:weather_hourly, primary_key: false) do
      add :weather_reading_id,
          references(:weather_readings,
            column: :id,
            name: "weather_hourly_weather_reading_id_fkey",
            type: :uuid
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :condition, :text
      add :icon, :text
      add :wind_speed, :float
      add :humidity, :bigint
      add :pop, :float
      add :feels_like, :float
      add :temp, :float
      add :forecast_time, :utc_datetime, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:weather_daily, primary_key: false) do
      add :weather_reading_id,
          references(:weather_readings,
            column: :id,
            name: "weather_daily_weather_reading_id_fkey",
            type: :uuid
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :condition, :text
      add :icon, :text
      add :sunset, :utc_datetime
      add :sunrise, :utc_datetime
      add :wind_speed, :float
      add :humidity, :bigint
      add :summary, :text
      add :pop, :float
      add :low, :float
      add :high, :float
      add :forecast_date, :utc_datetime, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `weather_daily` table without the `weather_daily_weather_reading_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:weather_daily)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `weather_hourly` table without the `weather_hourly_weather_reading_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:weather_hourly)

    alter table(:weather_readings) do
      remove :sunset
      remove :sunrise
      remove :wind_gust
      remove :wind_deg
      remove :wind_speed
      remove :visibility
      remove :clouds
      remove :uvi
      remove :dew_point
      remove :pressure
      remove :humidity
      # This is the `down` migration of the statement:
      #
      #     remove :forecast
      #

      # add :forecast, :map
    end
  end
end