defmodule FamilyDashboard.Repo.Migrations.AddNewsTickerSpeedSetting do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:settings) do
      add :news_ticker_chars_per_second, :bigint, null: false, default: 14
    end
  end

  def down do
    alter table(:settings) do
      remove :news_ticker_chars_per_second
    end
  end
end
