defmodule FamilyDashboard.Repo.Migrations.AddAlertsAlwaysShowCategories do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:settings) do
      # `default:` added by hand — ash_sqlite's codegen omitted it for this
      # attribute (a pre-existing quirk unrelated to this change: the current
      # snapshot shows `default: "nil"` for alerts_min_severity and
      # alerts_hidden_categories too, even though their original migrations
      # correctly embedded literal defaults). SQLite backfills existing rows
      # with a DEFAULT on ALTER TABLE ADD COLUMN, so this alone updates the
      # existing settings row — no separate data migration needed.
      add :alerts_always_show_categories, :text,
        null: false,
        default:
          "heat,flood,tornado,hurricane,tropical,tsunami,fire,wind,winter,freeze,coastal,marine"
    end
  end

  def down do
    alter table(:settings) do
      remove :alerts_always_show_categories
    end
  end
end
