defmodule FamilyDashboard.Repo.Migrations.AddSettingSchedulingKnobs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:settings) do
      # DB defaults match the resource attribute defaults; required by SQLite to
      # add NOT NULL columns to the populated settings table.
      add :calendar_sync_minutes, :bigint, null: false, default: 15
      add :weather_refresh_minutes, :bigint, null: false, default: 30
      add :sync_max_attempts, :bigint, null: false, default: 3
    end
  end

  def down do
    alter table(:settings) do
      remove :sync_max_attempts
      remove :weather_refresh_minutes
      remove :calendar_sync_minutes
    end
  end
end
