defmodule FamilyDashboard.Repo.Migrations.AddNewsFeedIdIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:news_feeds, [:id], name: "news_feeds_id_index")
  end

  def down do
    drop_if_exists unique_index(:news_feeds, [:id], name: "news_feeds_id_index")
  end
end
