defmodule FamilyDashboard.Repo.Migrations.AddWeatherStatus do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:settings) do
      add :weather_last_error, :text
      add :weather_last_attempted_at, :utc_datetime
    end
  end

  def down do
    alter table(:settings) do
      remove :weather_last_attempted_at
      remove :weather_last_error
    end
  end
end
