defmodule FamilyDashboard.Repo.Migrations.AddSettingTimeZone do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:settings) do
      # SQLite requires a non-NULL default to add a NOT NULL column to a
      # populated table; matches the resource attribute's default.
      add :time_zone, :text, null: false, default: "America/Chicago"
    end
  end

  def down do
    alter table(:settings) do
      remove :time_zone
    end
  end
end
