defmodule FamilyDashboard.Repo.Migrations.AddWeatherAlerts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:weather_alerts, primary_key: false) do
      add :weather_reading_id,
          references(:weather_readings,
            column: :id,
            name: "weather_alerts_weather_reading_id_fkey",
            type: :uuid
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :issued_at, :utc_datetime
      add :expires_at, :utc_datetime
      add :begins_at, :utc_datetime
      add :emergency, :boolean
      add :color, :text
      add :body, :text
      add :name, :text
      add :category, :text
      add :priority, :bigint
      add :severity, :text, null: false
      add :alert_type, :text
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `weather_alerts` table without the `weather_alerts_weather_reading_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:weather_alerts)
  end
end
