defmodule FamilyDashboard.Repo.Migrations.AddCalendarLastAttemptedAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:calendars) do
      add :last_attempted_at, :utc_datetime
    end
  end

  def down do
    alter table(:calendars) do
      remove :last_attempted_at
    end
  end
end
