defmodule FamilyDashboard.Repo.Migrations.CalendarUpsertIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:calendars, [:id], name: "calendars_id_index")
  end

  def down do
    drop_if_exists unique_index(:calendars, [:id], name: "calendars_id_index")
  end
end