defmodule FamilyDashboard.Repo.Migrations.AddAlertSettings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:settings) do
      add :alerts_min_severity, :text, null: false, default: "moderate"
      add :alerts_hidden_categories, :text, null: false, default: ""
      add :alerts_show_body, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:settings) do
      remove :alerts_show_body
      remove :alerts_hidden_categories
      remove :alerts_min_severity
    end
  end
end
