defmodule FamilyDashboard.Repo.Migrations.CreateDashboardResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:weather_readings, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :location_label, :text
      add :forecast, :map
      add :low, :float
      add :high, :float
      add :icon, :text
      add :condition, :text
      add :feels_like, :float
      add :temp, :float
      add :observed_at, :utc_datetime, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:settings, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :greeting, :text
      add :units, :text
      add :city_label, :text
      add :longitude, :float
      add :latitude, :float
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:events, primary_key: false) do
      add :calendar_id,
          references(:calendars, column: :id, name: "events_calendar_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :uid, :text, null: false
      add :location, :text
      add :all_day, :boolean
      add :ends_at, :utc_datetime
      add :starts_at, :utc_datetime, null: false
      add :title, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:calendars, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :last_error, :text
      add :last_synced_at, :utc_datetime
      add :active, :boolean, null: false
      add :color, :text
      add :ical_url, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:events, [:calendar_id, :uid, :starts_at],
             name: "events_unique_occurrence_index"
           )
  end

  def down do
    drop_if_exists unique_index(:events, [:calendar_id, :uid, :starts_at],
                     name: "events_unique_occurrence_index"
                   )

    drop table(:calendars)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `events` table without the `events_calendar_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:events)

    drop table(:settings)

    drop table(:weather_readings)
  end
end
