defmodule FamilyDashboard.Backup do
  @moduledoc """
  Exports/imports the hand-entered `calendars` + `news_feeds` + `settings`
  config as JSON — the only tables in the domain that aren't regenerated by a
  sync (see `FamilyDashboard.Sync`). Weather readings, events, and news items
  are deliberately excluded; they refresh themselves on the next scheduled
  sync. `setting` covers every operator-editable field on the singleton,
  including the alert-filtering and news-ticker knobs, not just location/sync
  cadence — see `writable_setting_fields/0` for the authoritative list (kept
  in sync with `FamilyDashboard.Setting`'s own `@writable`).

  Restore semantics:

    * calendars and news feeds are each upserted **by id** — an existing row
      is updated in place, one not yet in the DB is inserted, and any row not
      present in the backup is left alone. This preserves `events.calendar_id`
      and `news_items.news_feed_id` (a restore can never orphan a row).
    * the singleton setting is updated in place (or created if unseeded).
    * system-set status fields (`last_synced_at`/`last_attempted_at`/
      `last_error` on each restored calendar; `last_fetched_at`/`last_error`
      on each restored news feed; `weather_last_error`/
      `weather_last_attempted_at`/`daily_last_attempted_at` on the setting)
      are reset to `nil` rather than restored from a stale snapshot — the next
      heartbeat tick re-establishes real status within one cycle.
    * a backup taken before news feeds were included (no `"news_feeds"` key)
      restores fine — it's treated as an empty list, leaving existing feeds
      untouched.
  """

  require Logger

  alias FamilyDashboard.Dashboard

  @version 1

  @doc "Builds the exportable structure: version, timestamp, calendars, news feeds, setting."
  @spec export() :: map()
  def export do
    %{
      "version" => @version,
      "exported_at" => DateTime.utc_now() |> DateTime.to_iso8601(),
      "calendars" => Enum.map(Dashboard.list_calendars!(), &calendar_json/1),
      "news_feeds" => Enum.map(Dashboard.list_news_feeds!(), &news_feed_json/1),
      "setting" => setting_json(current_setting())
    }
  end

  @doc "`export/0` encoded as a pretty JSON string."
  @spec export_json() :: String.t()
  def export_json, do: export() |> Jason.encode!(pretty: true)

  @doc """
  Writes `json` to `<dir>/family_dashboard_backup_<timestamp>.json`, creating
  `dir` if needed. Returns `{:ok, path}` or `{:error, reason}` (a `File` error).
  """
  @spec write_to_disk(String.t(), String.t()) :: {:ok, String.t()} | {:error, term()}
  def write_to_disk(json, dir \\ backup_dir()) do
    with :ok <- File.mkdir_p(dir) do
      path = Path.join(dir, "family_dashboard_backup_#{timestamp()}.json")

      case File.write(path, json) do
        :ok -> {:ok, path}
        {:error, reason} -> {:error, reason}
      end
    end
  end

  @doc "The configured backup directory (see `config/runtime.exs`)."
  @spec backup_dir() :: String.t()
  def backup_dir do
    Application.get_env(:family_dashboard, :backup_dir) ||
      Path.expand("../../priv/backups", __DIR__)
  end

  @doc """
  Lists `.json` backups in `backup_dir/0` as `%{filename, mtime}`, newest
  first. A missing directory (no backup has ever been written yet) is a
  normal, expected state and returns `{:ok, []}` — any other `File.ls`
  failure (permission denied, unmounted volume, ...) is a real problem and
  is returned as `{:error, reason}` rather than silently looking identical
  to "no backups exist".
  """
  @spec list_backups() ::
          {:ok, [%{filename: String.t(), mtime: DateTime.t()}]} | {:error, term()}
  def list_backups do
    dir = backup_dir()

    case File.ls(dir) do
      {:ok, files} ->
        backups =
          files
          |> Enum.filter(&String.ends_with?(&1, ".json"))
          |> Enum.map(&%{filename: &1, mtime: file_mtime(Path.join(dir, &1))})
          |> Enum.sort_by(& &1.mtime, {:desc, DateTime})

        {:ok, backups}

      {:error, :enoent} ->
        {:ok, []}

      {:error, reason} ->
        {:error, reason}
    end
  end

  @doc """
  Reads a backup file by name from `backup_dir/0`. `filename` is reduced to
  its basename before joining, so a path-traversal attempt (`../../etc/passwd`)
  can only ever resolve to a file directly inside `backup_dir/0`.
  """
  @spec read_backup(String.t()) :: {:ok, String.t()} | {:error, term()}
  def read_backup(filename) do
    path = Path.join(backup_dir(), Path.basename(filename))
    File.read(path)
  end

  # A stat failure (e.g. the file vanished between `File.ls/1` and here) is
  # unverifiable — sink it to the bottom of the newest-first list with an
  # epoch timestamp rather than defaulting to "now", which would instead
  # promote an unverifiable file to the very top.
  defp file_mtime(path) do
    case File.stat(path, time: :posix) do
      {:ok, %File.Stat{mtime: mtime}} -> DateTime.from_unix!(mtime)
      {:error, _reason} -> ~U[1970-01-01 00:00:00Z]
    end
  end

  @doc """
  Restores calendars and news feeds (each upsert by id) and the setting
  (update-or-create) from a backup JSON string. Auto-exports the *current*
  state to disk first, as a safety net, before making any change — pass
  `skip_safety_export: true` to suppress this (used in tests). Returns
  `{:ok, summary}` or `{:error, reason}`.
  """
  @spec import_json(String.t(), keyword()) :: {:ok, map()} | {:error, term()}
  def import_json(json, opts \\ []) do
    with {:ok, decoded} <- Jason.decode(json),
         {:ok, data} <- validate(decoded) do
      unless opts[:skip_safety_export] do
        case write_to_disk(export_json()) do
          {:ok, _path} ->
            :ok

          {:error, reason} ->
            Logger.warning("Backup safety-export before restore failed: #{inspect(reason)}")
        end
      end

      calendars =
        Enum.map(data["calendars"], fn cal ->
          cal
          |> Map.take(writable_calendar_fields())
          |> Dashboard.upsert_calendar!()
        end)

      # Older backups predate news feeds and simply won't have this key.
      news_feeds =
        Enum.map(data["news_feeds"] || [], fn feed ->
          feed
          |> Map.take(writable_news_feed_fields())
          |> Dashboard.upsert_news_feed!()
        end)

      reset_calendar_status(calendars)
      reset_news_feed_status(news_feeds)
      restore_setting(data["setting"])

      {:ok, %{calendars_restored: length(calendars), news_feeds_restored: length(news_feeds)}}
    end
  end

  defp validate(%{"version" => @version, "calendars" => calendars, "setting" => setting} = data)
       when is_list(calendars) and is_map(setting) do
    {:ok, data}
  end

  defp validate(%{"version" => version}) when version != @version do
    {:error, {:invalid_backup, "unsupported version #{inspect(version)}"}}
  end

  defp validate(_data), do: {:error, {:invalid_backup, "missing calendars or setting"}}

  defp reset_calendar_status(calendars) do
    Enum.each(calendars, fn cal ->
      Dashboard.update_calendar!(cal, %{
        last_synced_at: nil,
        last_attempted_at: nil,
        last_error: nil
      })
    end)
  end

  defp reset_news_feed_status(feeds) do
    Enum.each(feeds, fn feed ->
      Dashboard.update_news_feed!(feed, %{last_fetched_at: nil, last_error: nil})
    end)
  end

  defp restore_setting(attrs) do
    setting_attrs = Map.take(attrs, writable_setting_fields())

    setting =
      case current_setting() do
        nil -> Dashboard.create_setting!(setting_attrs)
        existing -> Dashboard.update_setting!(existing, setting_attrs)
      end

    Dashboard.record_weather_status!(setting, %{
      weather_last_error: nil,
      weather_last_attempted_at: nil,
      daily_last_attempted_at: nil
    })
  end

  # Kept in sync with FamilyDashboard.Setting's own @writable list — every
  # operator-editable field, not just a subset, or a restore silently loses
  # whatever's missing here.
  defp writable_setting_fields do
    ~w(latitude longitude city_label units greeting time_zone calendar_sync_minutes
       weather_refresh_minutes daily_refresh_minutes sync_max_attempts alerts_min_severity
       alerts_hidden_categories alerts_always_show_categories alerts_show_body
       news_refresh_minutes news_retention_hours news_ticker_chars_per_second)
  end

  defp writable_calendar_fields, do: ~w(id name ical_url color active)

  defp writable_news_feed_fields, do: ~w(id url label enabled)

  defp calendar_json(cal) do
    %{
      "id" => cal.id,
      "name" => cal.name,
      "ical_url" => cal.ical_url,
      "color" => cal.color,
      "active" => cal.active,
      "last_synced_at" => datetime_json(cal.last_synced_at),
      "last_attempted_at" => datetime_json(cal.last_attempted_at),
      "last_error" => cal.last_error
    }
  end

  defp news_feed_json(feed) do
    %{
      "id" => feed.id,
      "url" => feed.url,
      "label" => feed.label,
      "enabled" => feed.enabled,
      "last_fetched_at" => datetime_json(feed.last_fetched_at),
      "last_error" => feed.last_error
    }
  end

  defp setting_json(nil), do: %{}

  defp setting_json(setting) do
    %{
      "latitude" => setting.latitude,
      "longitude" => setting.longitude,
      "city_label" => setting.city_label,
      "units" => setting.units,
      "greeting" => setting.greeting,
      "time_zone" => setting.time_zone,
      "calendar_sync_minutes" => setting.calendar_sync_minutes,
      "weather_refresh_minutes" => setting.weather_refresh_minutes,
      "daily_refresh_minutes" => setting.daily_refresh_minutes,
      "sync_max_attempts" => setting.sync_max_attempts,
      "alerts_min_severity" => setting.alerts_min_severity,
      "alerts_hidden_categories" => setting.alerts_hidden_categories,
      "alerts_always_show_categories" => setting.alerts_always_show_categories,
      "alerts_show_body" => setting.alerts_show_body,
      "news_refresh_minutes" => setting.news_refresh_minutes,
      "news_retention_hours" => setting.news_retention_hours,
      "news_ticker_chars_per_second" => setting.news_ticker_chars_per_second,
      # Exported for human readability only; ignored on import (see @moduledoc).
      "weather_last_error" => setting.weather_last_error,
      "weather_last_attempted_at" => datetime_json(setting.weather_last_attempted_at),
      "daily_last_attempted_at" => datetime_json(setting.daily_last_attempted_at)
    }
  end

  defp datetime_json(nil), do: nil
  defp datetime_json(%DateTime{} = dt), do: DateTime.to_iso8601(dt)

  defp current_setting do
    case Dashboard.current_setting() do
      {:ok, setting} -> setting
      _ -> nil
    end
  end

  defp timestamp do
    DateTime.utc_now() |> DateTime.to_iso8601() |> String.replace(~r/[:.]/, "-")
  end
end
