defmodule FamilyDashboard.Backup do
  @moduledoc """
  Exports/imports the hand-entered `calendars` + `settings` config as JSON —
  the only two tables in the domain that aren't regenerated by a sync (see
  `FamilyDashboard.Sync`). Weather readings and events are deliberately
  excluded; they refresh themselves on the next scheduled sync.

  Restore semantics:

    * calendars are upserted **by id** — an existing calendar is updated in
      place, a calendar not yet in the DB is inserted, and any calendar not
      present in the backup is left alone. This preserves `events.calendar_id`
      (a restore can never orphan an event).
    * the singleton setting is updated in place (or created if unseeded).
    * system-set sync-status fields (`last_synced_at`, `last_attempted_at`,
      `last_error` on each restored calendar; `weather_last_error`,
      `weather_last_attempted_at`, `daily_last_attempted_at` on the setting)
      are reset to `nil` rather than restored from a stale snapshot — the next
      heartbeat tick re-establishes real status within one cycle.
  """

  require Logger

  alias FamilyDashboard.Dashboard

  @version 1

  @doc "Builds the exportable structure: version, timestamp, calendars, setting."
  @spec export() :: map()
  def export do
    %{
      "version" => @version,
      "exported_at" => DateTime.utc_now() |> DateTime.to_iso8601(),
      "calendars" => Enum.map(Dashboard.list_calendars!(), &calendar_json/1),
      "setting" => setting_json(current_setting())
    }
  end

  @doc "`export/0` encoded as a pretty JSON string."
  @spec export_json() :: String.t()
  def export_json, do: export() |> Jason.encode!(pretty: true)

  @doc """
  Writes `json` to `<dir>/family_dashboard_backup_<timestamp>.json`, creating
  `dir` if needed. Returns `{:ok, path}` or `{:error, reason}` (a `File` error).
  """
  @spec write_to_disk(String.t(), String.t()) :: {:ok, String.t()} | {:error, term()}
  def write_to_disk(json, dir \\ backup_dir()) do
    with :ok <- File.mkdir_p(dir) do
      path = Path.join(dir, "family_dashboard_backup_#{timestamp()}.json")

      case File.write(path, json) do
        :ok -> {:ok, path}
        {:error, reason} -> {:error, reason}
      end
    end
  end

  @doc "The configured backup directory (see `config/runtime.exs`)."
  @spec backup_dir() :: String.t()
  def backup_dir do
    Application.get_env(:family_dashboard, :backup_dir) ||
      Path.expand("../../priv/backups", __DIR__)
  end

  @doc """
  Restores calendars (upsert by id) and the setting (update-or-create) from a
  backup JSON string. Auto-exports the *current* state to disk first, as a
  safety net, before making any change — pass `skip_safety_export: true` to
  suppress this (used in tests). Returns `{:ok, summary}` or `{:error, reason}`.
  """
  @spec import_json(String.t(), keyword()) :: {:ok, map()} | {:error, term()}
  def import_json(json, opts \\ []) do
    with {:ok, decoded} <- Jason.decode(json),
         {:ok, data} <- validate(decoded) do
      unless opts[:skip_safety_export] do
        case write_to_disk(export_json()) do
          {:ok, _path} ->
            :ok

          {:error, reason} ->
            Logger.warning("Backup safety-export before restore failed: #{inspect(reason)}")
        end
      end

      calendars =
        Enum.map(data["calendars"], fn cal ->
          cal
          |> Map.take(writable_calendar_fields())
          |> Dashboard.upsert_calendar!()
        end)

      reset_calendar_status(calendars)
      restore_setting(data["setting"])

      {:ok, %{calendars_restored: length(calendars)}}
    end
  end

  defp validate(%{"version" => @version, "calendars" => calendars, "setting" => setting} = data)
       when is_list(calendars) and is_map(setting) do
    {:ok, data}
  end

  defp validate(%{"version" => version}) when version != @version do
    {:error, {:invalid_backup, "unsupported version #{inspect(version)}"}}
  end

  defp validate(_data), do: {:error, {:invalid_backup, "missing calendars or setting"}}

  defp reset_calendar_status(calendars) do
    Enum.each(calendars, fn cal ->
      Dashboard.update_calendar!(cal, %{
        last_synced_at: nil,
        last_attempted_at: nil,
        last_error: nil
      })
    end)
  end

  defp restore_setting(attrs) do
    setting_attrs = Map.take(attrs, writable_setting_fields())

    setting =
      case current_setting() do
        nil -> Dashboard.create_setting!(setting_attrs)
        existing -> Dashboard.update_setting!(existing, setting_attrs)
      end

    Dashboard.record_weather_status!(setting, %{
      weather_last_error: nil,
      weather_last_attempted_at: nil,
      daily_last_attempted_at: nil
    })
  end

  defp writable_setting_fields do
    ~w(latitude longitude city_label units greeting time_zone calendar_sync_minutes weather_refresh_minutes daily_refresh_minutes sync_max_attempts)
  end

  defp writable_calendar_fields, do: ~w(id name ical_url color active)

  defp calendar_json(cal) do
    %{
      "id" => cal.id,
      "name" => cal.name,
      "ical_url" => cal.ical_url,
      "color" => cal.color,
      "active" => cal.active,
      "last_synced_at" => datetime_json(cal.last_synced_at),
      "last_attempted_at" => datetime_json(cal.last_attempted_at),
      "last_error" => cal.last_error
    }
  end

  defp setting_json(nil), do: %{}

  defp setting_json(setting) do
    %{
      "latitude" => setting.latitude,
      "longitude" => setting.longitude,
      "city_label" => setting.city_label,
      "units" => setting.units,
      "greeting" => setting.greeting,
      "time_zone" => setting.time_zone,
      "calendar_sync_minutes" => setting.calendar_sync_minutes,
      "weather_refresh_minutes" => setting.weather_refresh_minutes,
      "daily_refresh_minutes" => setting.daily_refresh_minutes,
      "sync_max_attempts" => setting.sync_max_attempts,
      # Exported for human readability only; ignored on import (see @moduledoc).
      "weather_last_error" => setting.weather_last_error,
      "weather_last_attempted_at" => datetime_json(setting.weather_last_attempted_at),
      "daily_last_attempted_at" => datetime_json(setting.daily_last_attempted_at)
    }
  end

  defp datetime_json(nil), do: nil
  defp datetime_json(%DateTime{} = dt), do: DateTime.to_iso8601(dt)

  defp current_setting do
    case Dashboard.current_setting() do
      {:ok, setting} -> setting
      _ -> nil
    end
  end

  defp timestamp do
    DateTime.utc_now() |> DateTime.to_iso8601() |> String.replace(~r/[:.]/, "-")
  end
end
